### ISSUE TITLE
Bing Api wants Dates in specific format

### ISSUE THREAD

**Issue by ahuggins** [AgencyPMG/bing-ads-php#8]
The current generated Bing SDK looks to format Date Time strings using the `::ATOM` format, but this does not seem to be working with the Bing API. But because the SDK is generated using the https://github.com/wsdl2phpgenerator/wsdl2phpgenerator and that package defaults to using the `::ATOM` format. this may be a tricky change to make.

In somewhat related news, @chrisguitarguy, opened a PR to that package in order to make extending it easier: https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/pull/284

It has not been merged yet.

Not sure what the format is called but was able to find on the Carbon library some existing methods that appear to match the format:

```
echo $dt->toISOString();            // 2019-02-01T03:45:27.612584Z

echo $dt->toIso8601ZuluString();    // 2019-02-01T03:45:27Z
```

Carbon docs: https://carbon.nesbot.com/docs/#api-commonformats

**Comment by chrisguitarguy** [comment]
Docs: https://docs.microsoft.com/en-us/advertising/campaign-management-service/offlineconversion?view=bingads-12
